### ISSUE TITLE
Meta thread for any potential future for trelby

### ISSUE THREAD

**Issue by makrbrk** [trelby/trelby#36]
This started off as a list of changes to trelby, but I decided to axe that because it would be almost a rewrite so a new program should be made instead. I'm currently balancing out the pros and cons of C vs Python if I was to make my own potential continuation of trelby. But that's just on the idea board for now.

**Comment by makrbrk** [comment]
I think the JSON idea will work out great. Fade In uses the OpenScreenplay XML format, which stores in it margin information along with user settings. It can be changed and nobody will really notice a difference if switched to JSON.

**Comment by UnisTorvalds** [comment]
Why not Fountain?  Trelby already parses Fountain on import (though at present it lacks a couple of its features like itallics and simultaneous dialogue).  Trelby could become the first (to my knowledge) fully-featured wysiwyg Fountain editor.

**Comment by rcentros** [comment]
For what it's worth... In defense of Trelby "as is."

I've used Trelby for most of my screenplay writing for the last 12 years, but I've tried (or used) many others in the past (and present). I own Fade In (bought it mostly because they supported Linux) have installed Kit Scenarist, Story Architect (Starc), WriterSolo (the offline version of WriterDuet), Fountain-Mode in eMacs, Better Fountain in VSCode, Beat! on the Mac, Highland 2 and Slugline (also on the Mac, all of the last three based on Fountain). I've used in the past, ScriptWare (for DOS and Windows), ScriptThing (for DOS and Windows), Movie Magic Screenwriter, Blyte (the original Trelby, as a beta tester), YouMeScript, Celtx (the one that could be downloaded), 'Afterwriting, Screenplain, Sophocles, Arc Studio, WriterDuet, SceneWriter, and I've tried and disliked Final Draft on both the Mac and Windows... and there are others I can't remember.

None of these, in my mind, compare to the simplicity, speed and "beauty" of Trelby for writing the first draft of a screenplay. I like that the Display Fonts and PDF Fonts are separate, for example. This allows me to write with any mono-space font, knowing that PDF output will be a standard (Courier) screenplay format.

I like that I can customize Trelby to use whatever color theme I want. I normally use a theme that uses different colors for different elements (something I picked up from Fountain-Mode). As far as I know, this is completely unique -- not found in any other screenplay application (unless Fountain-Mode and Better Fountain are considered "applications"). I like that I can Load a bold or double-spaced scene heading, or not, or change to one of several fonts, using one click to Load. I can set up these .sconf (Script Config) files for any font I want or customized format I want.

I also like the simplicity of text-based configuration files for both .config (Configuration) and .sconf files. And I like the Trelby file format. It's fast and (seemingly) simple, and I've never had a corruption issue. (I constantly see corruption issues with files in XML formats like Final Draft -- and once or twice in Fade In.) The header gets messed up and you've lost your file, unless you can fix it. (Don't know anything about the JSON file format.)

There are quite a few people I've "met" online, who also like the simplicity, UI and "directness" of Trelby (as is).

I guess that, maybe, I'm a Trelby Luddite, but I would really like to see Trelby (at least one version of it) stay the same as it is now. I love that it's being updated for modern Linux distributions, but I really don't want it to turn into another version of Fade In, or WriterDuet or Final Draft. (Not that it would, but I like Trelby the way it is.)

I'm not a programmer, so I don't understand the limitations of Trelby development as it now stands. I don't know if Unicode can be (or has been) implemented. (A feature I see mentioned a lot in connection with Trelby.) I don't know the limitations of the file format (as is) in regards to production features. I realize that Trelby is "quirky" and works differently than other applications -- but I find that some of these differences are superior to other applications. I would definitely like to see the Configuration files remain separate, because the division between the application and the script configuration works well for me. (It's one of the reasons I really like Trelby.)

But I understand that others want more. Often mentioned are the production features, text zooming (without changing the display font) and Unicode support, to name three.

For those who want those changes, maybe a fork of Trelby to something like "Trelby Pro" -- so hobbyists, like me, could continue using Trelby (that we like) and a new Trelby could be developed for those who want Trelby to be more like Fade In or one of the others. This could be something like what happened with Kit Scenarist when they went to Story Architect (Starc). Kit Scenarist is still available, but the development emphasis has been put on the new application, Starc.

At any rate, it's what I would prefer. I realize that I don't really have much say in this as I'm not a developer, but it's a "compromise" that some may like to see.

Another benefit of forking to "Trelby Pro" is that new features and formats could be tested in isolation while "Trelby Classic" would be stable.

For what it's worth. Sorry for rambling.

**Comment by makrbrk** [comment]
@UnisTorvalds 
The fountain spec would require breakage to add stuff it doesn't have like production features.

@rcentros 
I think screenwriting deserves a libre equiv to fade in pro or final draft. Rather than have two different versions of trelby, keep one. I'm open to keeping a plain text format for trelby files, I had also in mind of nroff style dot commands that's similar to what trelby has right now. I think this can work out for the both of us.

**Comment by makrbrk** [comment]
@rcentros 
But since you brought it up, I thought since I'm making radical changes, toy with a spiritual successor [here](https://github.com/makrbrk/lobbies) using the same license and toolkit as trelby has. Just to experiment and let limburgher cherry pick what she wants to implement.

**Comment by makrbrk** [comment]
@rcentros 
If you're wondering about the delete comment, I change the repo to [owlmite](https://github.com/makrbrk/owlmite) to toy with a possible spiritual successor. Differences being this one is under GPLv3 and it possible might not use wxpython in the end. I'll let time be the judge.

**Comment by rcentros** [comment]
@makrbrk 
I understand what you're thinking. I guess I'm just nostalgic and like things to stay the same. I've written in the neighborhood of 400 shorts using ScriptThing and then Trelby — almost exclusively in Trelby since 2012. I guess I like familiarity.  Even my posted comment was written in WordStar for DOS (using DOSBox-X) — so it's not just the "old" Trelby I want to hang on to. Whatever direction this goes, I thank you developers for all your work on this. If not for the Trelby updates during the last few years, I wouldn't be using Trelby at all.

So, thank you — and thanks to all those working on Trelby. I still think it's the best screenwriting application made.

I'll try to hold off commenting further here, unless I find bugs (or what I think are bugs).

**Comment by limburgher** [comment]
What's the argument in favor of merging script and main configs? It seems like having per-script configurations is a feature some users really like. I'm also not sure git integration is necessary, but it depends on the form that takes I guess.

**Comment by makrbrk** [comment]
> What's the argument in favor of merging script and main configs? It seems like having per-script configurations is a feature some users really like. I'm also not sure git integration is necessary, but it depends on the form that takes I guess.

The first one, was just spitballing ideas. I'm going to scratch it out as not happening. But the git integration was something that I wanted to personally see, because I simply love git and it's a nice bonus to have.

Now, for my next question, are you okay with transitioning the trelby format to JSON/XML/YAML? Something that could make it more flexible for more production features?

**Comment by makrbrk** [comment]
@rcentros 
You got nothing to worry about, I decided against making a 'spiritual successor' in favor of adding a few enhancements to trelby instead. Probably because my OCD tendencies get the best of me and I could be spending time on other things.

**Comment by limburgher** [comment]
> > What's the argument in favor of merging script and main configs? It seems like having per-script configurations is a feature some users really like. I'm also not sure git integration is necessary, but it depends on the form that takes I guess.
> 
> The first one, was just spitballing ideas. I'm going to scratch it out as not happening. But the git integration was something that I wanted to personally see, because I simply love git and it's a nice bonus to have.
> 
> Now, for my next question, are you okay with transitioning the trelby format to JSON/XML/YAML? Something that could make it more flexible for more production features?

In principle, yes. But file format changes should be done carefully and as little as possible. If we can do it in a way that if I write a script with, say, 2.4.11 that has locking, and I send it to Alice who has 2.4.6 without it, her Trelby ignores it, that would be better.

**Comment by makrbrk** [comment]
> > > What's the argument in favor of merging script and main configs? It seems like having per-script configurations is a feature some users really like. I'm also not sure git integration is necessary, but it depends on the form that takes I guess.
> > 
> > 
> > The first one, was just spitballing ideas. I'm going to scratch it out as not happening. But the git integration was something that I wanted to personally see, because I simply love git and it's a nice bonus to have.
> > Now, for my next question, are you okay with transitioning the trelby format to JSON/XML/YAML? Something that could make it more flexible for more production features?
> 
> In principle, yes. But file format changes should be done carefully and as little as possible. If we can do it in a way that if I write a script with, say, 2.4.11 that has locking, and I send it to Alice who has 2.4.6 without it, her Trelby ignores it, that would be better.

Hmmmm.... Doesn't python have the ability to insert something not at the very bottom? Like in a dedicated section? If so, I would say just make a new section at the bottom for revision marks, and locked stuff. And would trelby do anything if it sees an unknown key?

**Comment by limburgher** [comment]
In an ini config file, yes. Weren't we discussing script files?

**Comment by makrbrk** [comment]
Wait, I was talking about the .trelby format spec. I was asking if an older version of trelby sees an unknown key, does it ignore it?

**Comment by limburgher** [comment]
I don't know. I'd think something between #Begin-Config and #End-Config that was unknown might throw a warning but I haven't experimented.

**Comment by anilgulecha** [comment]
Folks, Trelby file format is simple (including the UX that years later if you don't have Trelby, open it in a file editor and you can see your script right there and copy it elsewhere, etc).

I recommend against changing file format that is backward incompatible. So incrementally adding more is fine - but we should ensure that a trelby file in a newer version should still open and work in the older one.

@rcentros has captured the original intent correctly, a simple fast and amazing place to write the script. I agree that the FOSS world needs a open "pro" like equivalent of final draft, but IMO that's pretty much writing a new application, rather than converting Trelby to it.

If anyone is adventurous enough to go down this path, I'm happy to catch-up and share learning (and recommendations) on what stack and methods they can pick :)

**Comment by makrbrk** [comment]
> Folks, Trelby file format is simple (including the UX that years later if you don't have Trelby, open it in a file editor and you can see your script right there and copy it elsewhere, etc).
> 
> I recommend against changing file format that is backward incompatible. So incrementally adding more is fine - but we should ensure that a trelby file in a newer version should still open and work in the older one.
> 
> @rcentros has captured the original intent correctly, a simple fast and amazing place to write the script. I agree that the FOSS world needs a open "pro" like equivalent of final draft, but IMO that's pretty much writing a new application, rather than converting Trelby to it.
> 
> If anyone is adventurous enough to go down this path, I'm happy to catch-up and share learning (and recommendations) on what stack and methods they can pick :)

Would you recommend sticking with wxpython? Or going to PyGObject (GTK) or PyQt6/PySide6? I would love to contribute to a new version of trelby, but not sure where to start.

**Comment by makrbrk** [comment]
@rcentros 
@anilgulecha 
If you got any objections, I really think we should avoid GTK (PyGObject) and Qt6 (PySide6/PyQt6) bindings directly, only because I've had mixed experiences with having to fight both of them as well as they're very fast moving targets, wxPython would be less playing catch up. But that's just how I see it.

If this repo I [made](https://github.com/makrbrk/kaiseru) goes anywhere, we can talk about it possibly being trelby: the next generation.

**Comment by makrbrk** [comment]
Though, I'll admit a huge load of improvements from GTK3->GTK4 could be extremely beneficial.

**Comment by janopae** [comment]
Some thoughts about JSON for .trelby files:

- This would be a huge breaking change. New trelby files couldn't be opened in older versions of the program. Other programs that implement support for .trelby files (like KITScenarist) would lose support for them. If we'd want to stay compatible with old .trelby files, we'd need to maintain 2 loaders for them depending on the format version.
- JSON is not really human readable in my opinion as it doesn't support comments. JSON is for sending serialised data over the network, and though I know it is sometimes used for configuration files to be edited by humans, I consider this a mistake in most cases.
- The current trelby file format can be read and edited with a text editor almost like markdown, I think that is as human readable as it can get for a script file format.
- The Trelby file format is more or less the "heart" of Trelby – the program is built around it, a lot of people have files in that format, other programs support importing it. It is one of the things that keep Trelby relevant. If we got rid of it, we could as well start over writing yet another screenplay program.
- I don't really see the benefits of using JSON for screenplays tbo

**Comment by makrbrk** [comment]
> Some thoughts about JSON for .trelby files:
> 
>     * This would be a huge breaking change. New trelby files couldn't be opened in older versions of the program. Other programs that implement support for .trelby files (like KITScenarist) would lose support for them. If we'd want to stay compatible with old .trelby files, we'd need to maintain 2 loaders for them depending on the format version.
> 
>     * JSON is not really human readable in my opinion as it doesn't support comments. JSON is for sending serialised data over the network, and though I know it is sometimes used for configuration files to be edited by humans, I consider this a mistake in most cases.
> 
>     * The current trelby file format can be read and edited with a text editor almost like markdown, I think that is as human readable as it can get for a script file format.
> 
>     * The Trelby file format is more or less the "heart" of Trelby – the program is built around it, a lot of people have files in that format, other programs support importing it. It is one of the things that keep Trelby relevant. If we got rid of it, we could as well start over writing yet another screenplay program.
> 
>     * I don't really see the benefits of using JSON for screenplays tbo

The changes plan got axed, it would be almost a rewrite if this was to happen.

**Comment by janopae** [comment]
There's a new Subreddit for Trelby, but it lacks discussions: https://www.reddit.com/r/Trelby/

Maybe you could move your discussion there and start some life in that subreddit? Then, we could close this issue, as it is not really an actual issue :)

**Comment by makrbrk** [comment]
> There's a new Subreddit for Trelby, but it lacks discussions: https://www.reddit.com/r/Trelby/
> 
> Maybe you could move your discussion there and start some life in that subreddit? Then, we could close this issue, as it is not really an actual issue :)

Right, I'll just close it.
